import { Opshtina } from './opshtina';

export const OPSHTINI: Opshtina[] = [
  {id: "skopje", name: "Скопје", borders: ["ilinden", "arachinovo", "studenichani", "sopishte", "lipkovo" , "zhelino" , "jegunovce", "chucher_sandevo", "petrovec"]},
  {id: "arachinovo", name: "Арачиново", borders: ["skopje", "ilinden", "kumanovo","lipkovo"]},
  {id: "berovo", name: "Берово", borders: ["pehchevo", "delchevo", "vinica", "radovish", "vasilevo", "bosilovo", "novo_selo"]},
  {id: "bitola", name: "Битола", borders: ["mogila", "demir_hisar", "resen", "novaci"]},
  {id: "bogdanci", name: "Богданци", borders: ["gevgelija", "dojran", "valandovo"]},
  {id: "bogovinje", name: "Боговиње", borders: ["tetovo", "brvenica", "vrapchishte"]},
  {id: "bosilovo", name: "Босилово", borders: ["strumica", "novo_selo", "vasilevo", "berovo"]},
  {id: "brvenica", name: "Брвеница", borders: ["tetovo", "bogovinje", "vrapchishte","zhelino", "makedonski_brod", "gostivar"]},
  {id: "valandovo", name: "Валандово", borders: ["bogdanci", "dojran", "gevgelija", "strumica","demir_kapija", "konche"]},
  {id: "vasilevo", name: "Василево", borders: ["strumica", "bosilovo", "radovish", "berovo", "konche"]},
  {id: "veles", name: "Велес", borders: ["gradsko", "lozovo", "sveti_nikole", "zelenikovo", "chashka", "petrovec"]},
  {id: "vinica", name: "Виница", borders: ["kochani", "makedonska_kamenica", "delchevo", "berovo", "radovish", "karbinci", "zrnovci"]},
  {id: "vrapchishte", name: "Врапчиште", borders: ["bogovinje", "brvenica", "gostivar"]},
  {id: "gevgelija", name: "Гевгелија", borders: ["bogdanci", "demir_kapija", "valandovo", "kavadarci"]},
  {id: "gostivar", name: "Гостивар", borders: ["vrapchishte", "brvenica", "makedonski_brod", "mavrovo_rostushe", "kichevo"]},
  {id: "gradsko", name: "Градско", borders: ["veles", "chashka", "lozovo", "shtip", "negotino", "rosoman"]},
  {id: "debarca", name: "Дебaрца", borders: ["ohrid", "kichevo", "struga", "demir_hisar"]},
  {id: "delchevo", name: "Делчево", borders: ["vinica", "pehchevo", "berovo","makedonska_kamenica"]},
  {id: "demir_kapija", name: "Демир Капија", borders: ["kavadarci", "valandovo", "negotino", "gevgelija", "konche"]},
  {id: "demir_hisar", name: "Демир Хисар", borders: ["bitola", "mogila", "kichevo", "resen", "ohrid", "debarca", "krushevo"]},
  {id: "dojran", name: "Дојран", borders: ["bogdanci", "valandovo"]},
  {id: "zelenikovo", name: "Зелениково", borders: ["studenichani", "veles", "chashka", "petrovec"]},
  {id: "zhelino", name: "Желино", borders: ["tetovo", "brvenica", "makedonski_brod", "skopje", "sopishte", "jegunovce"]},
  {id: "ilinden", name: "Илинден", borders: ["skopje", "arachinovo", "kumanovo", "petrovec"]},
  {id: "jegunovce", name: "Јегуновце", borders: ["tetovo", "tearce", "skopje", "zhelino"]},
  {id: "kavadarci", name: "Кавадарци", borders: ["demir_kapija", "negotino", "gevgelija", "rosoman", "chashka", "prilep"]},
  {id: "kichevo", name: "Кичево", borders: ["gostivar", "makedonski_brod", "demir_hisar", "debarca", "mavrovo_rostushe", "plasnica", "debar", "krushevo"]},
  {id: "kochani", name: "Кочани", borders: ["kriva_palanka", "makedonska_kamenica", "vinica", "cheshinovo_obleshevo", "kratovo", "zrnovci", "probishtip"]},
  {id: "kratovo", name: "Кратово", borders: ["rankovce", "kumanovo", "kochani", "staro_negorichane", "kriva_palanka", "probishtip", "sveti_nikole"]},
  {id: "kriva_palanka", name: "Крива Паланка", borders: ["rankovce", "kratovo", "kochani", "makedonska_kamenica"]},
  {id: "krushevo", name: "Крушево", borders: ["demir_hisar", "krivogashtani", "mogila", "dolneni", "makedonski_brod", "plasnica", "kichevo"]},
  {id: "kumanovo", name: "Куманово", borders: ["kratovo", "arachinovo", "ilinden", "lipkovo", "staro_negorichane", "sveti_nikole", "petrovec"]},
  {id: "lozovo", name: "Лозово", borders: ["sveti_nikole", "gradsko", "shtip", "veles"]},
  {id: "mogila", name: "Могила", borders: ["bitola", "prilep", "novaci", "krivogashtani", "krushevo", "demir_hisar"]},
  {id: "novo_selo", name: "Ново Село", borders: ["bosilovo", "strumica", "berovo"]},
  {id: "ohrid", name: "Охрид", borders: ["resen", "debarca", "demir_hisar"]},
  {id: "pehchevo", name: "Пехчево", borders: ["berovo", "delchevo"]},
  {id: "prilep", name: "Прилеп", borders: ["novaci", "krivogashtani", "mogila", "dolneni", "chashka", "kavadarci"]},
  {id: "radovish", name: "Радовиш", borders: ["konche", "vasilevo", "shtip", "karbinci", "vinica", "berovo"]},
  {id: "resen", name: "Ресен", borders: ["bitola", "ohrid", "demir_hisar"]},
  {id: "struga", name: "Струга", borders: ["vevchani", "debarca", "centar_zhupa", "debar"]},
  {id: "tetovo", name: "Тетово", borders: ["zhelino", "brvenica", "bogovinje", "tearce", "jegunovce"]},
  {id: "shtip", name: "Штип", borders: ["negotino", "konche", "radovish", "gradsko", "lozovo", "sveti_nikole", "probishtip", "karbinci"]},

  {id: "tearce", name: "Теарце", borders: ["tetovo", "jegunovce"]},
  {id: "mavrovo_rostushe", name: "Маврово и Ростуша", borders: ["gostivar", "kichevo", "debar"]},
  {id: "debar", name: "Дебар", borders: ["mavrovo_rostushe", "centar_zhupa", "struga", "kichevo"]},
  {id: "centar_zhupa", name: "Центар Жупа", borders: ["debar", "struga"]},
  {id: "vevchani", name: "Вевчани", borders: ["struga"]},
  {id: "demir_hisar", name: "Демир Хисар", borders: ["bitola", "resen", "krushevo", "mogila", "kichevo", "ohrid", "debarca"]},
  {id: "novaci", name: "Новаци", borders: ["bitola", "mogila", "prilep"]},
  {id: "chucher_sandevo", name: "Чучер Сандево", borders: ["skopje", "lipkovo"]},
  {id: "lipkovo", name: "Липково", borders: ["kumanovo", "skopje", "chucher_sandevo", "arachinovo"]},
  {id: "staro_negorichane", name: "Старо Нагоричане", borders: ["rankovce", "kumanovo", "kratovo"]},
  {id: "rankovce", name: "Ранковце", borders: ["kriva_palanka", "kratovo", "staro_negorichane"]},
  {id: "sopishte", name: "Сопиште", borders: ["skopje", "studenichani", "zhelino", "makedonski_brod"]},
  {id: "makedonska_kamenica", name: "Македонска Каменица", borders: ["delchevo", "vinica", "kochani", "kriva_palanka"]},

  {id: "strumica", name: "Струмица", borders: ["bosilovo", "novo_selo", "valandovo", "konche", "vasilevo"]},
  {id: "konche", name: "Конче", borders: ["radovish", "strumica", "vasilevo", "valandovo", "demir_kapija", "negotino", "shtip"]},
  {id: "negotino", name: "Неготино", borders: ["kavadarci", "demir_kapija", "rosoman", "shtip", "gradsko", "konche"]},
  {id: "rosoman", name: "Росоман", borders: ["negotino", "kavadarci", "gradsko", "chashka"]},
  {id: "krivogashtani", name: "Кривогаштани", borders: ["prilep", "dolneni", "krushevo", "mogila"]},
  {id: "dolneni", name: "Долнени", borders: ["prilep", "krivogashtani", "krushevo", "makedonski_brod", "chashka"]},
  {id: "chashka", name: "Чашка", borders: ["veles", "makedonski_brod", "prilep", "dolneni", "studenichani", "zelenikovo", "veles", "gradsko", "rosoman", "kavadarci"]},
  {id: "plasnica", name: "Пласница", borders: ["kichevo", "krushevo", "makedonski_brod"]},
  {id: "makedonski_brod", name: "Македонски Брод", borders: ["kichevo", "krushevo", "plasnica", "dolneni", "chashka", "studenichani", "sopishte", "zhelino", "brvenica", "gostivar"]},
  {id: "studenichani", name: "Студеничани", borders: ["skopje", "zelenikovo", "sopishte", "petrovec", "chashka", "makedonski_brod"]},
  {id: "petrovec", name: "Петровец", borders: ["skopje", "ilinden", "studenichani", "zelenikovo", "veles", "sveti_nikole", "kumanovo"]},
  {id: "sveti_nikole", name: "Свети Николе", borders: ["shtip", "lozovo", "veles", "petrovec", "kumanovo", "kratovo", "probishtip"]},
  {id: "probishtip", name: "Пробиштип", borders: ["kratovo", "shtip", "cheshinovo_obleshevo", "kochani", "karbinci", "sveti_nikole"]},
  {id: "cheshinovo_obleshevo", name: "Чешиново-Облешево", borders: ["kochani", "zrnovci", "karbinci", "probishtip"]},
  {id: "zrnovci", name: "Зрновци", borders: ["cheshinovo_obleshevo", "vinica", "kochani", "karbinci"]},
  {id: "karbinci", name: "Карбинци", borders: ["shtip", "probishtip", "cheshinovo_obleshevo", "zrnovci", "vinica", "radovish"]}
]
